/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.ApiRequest;

@Api(value = "commitPayment", description = "the commitPayment API")
public interface CommitPaymentApi {

    @ApiOperation(value = "Commit the Payment Information", notes = "", response = ApiResponseMessage.class, tags={ "API-Request", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operation successful for the API call.  Details to be looked up in the API call.", response = Object.class),
        @ApiResponse(code = 201, message = "Created", response = Void.class),
        @ApiResponse(code = 400, message = "Bad Request or Malformed Request for the API call.", response = Void.class),
        @ApiResponse(code = 401, message = "Authentication credentials not found in the API call.", response = Void.class),
        @ApiResponse(code = 403, message = "Not Authorized for the API call.", response = Void.class),
        @ApiResponse(code = 404, message = "Payment identifier not found.", response = Void.class),
        @ApiResponse(code = 408, message = "Request Timed out during the API call.", response = Void.class),
        @ApiResponse(code = 500, message = "System Error occurred during the API call.", response = Void.class) })
    
    @RequestMapping(value = "/commitPayment",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/xml", "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ApiResponseMessage> postCommitPayment(@ApiParam(value = "Commit the Payment Information" ,required=true )  @Valid @RequestBody ApiRequest body);

}
